#!/bin/sh

readonly LOG_FILE=tex.log

for tex_file in *.tex
do
    [ -e "$tex_file" ] || echo TeX file not exist. && exit
    main_tex="$(grep '\\documentclass' "$tex_file")"
    if [ -n "$main_tex" ]; then
        break
    fi
done

platex "${tex_file%.*}".tex >$LOG_FILE 2>&1
exitStatus=$?
dvipdfmx "${tex_file%.*}".dvi >>$LOG_FILE 2>&1

if [ $exitStatus -eq 0 ]; then
    open "${tex_file%.*}".pdf
else
    cat $LOG_FILE
fi
