#!/bin/sh

texName=$1
scful=0

echo $texName > stOut-1
sed -e 's/.tex//' stOut-1 > stOut-2
sed -e 's/\.//' stOut-2 > stOut-3

texName=`cat stOut-3`
rm stOut-[1-3]

platex $texName.tex > tex.log 2>&1
exit=$?

dvipdfmx $texName.dvi >> tex.log 2>&1

if [ $exit -eq $scful ]
then
    open $texName.pdf
else
    cat tex.log
fi
