#!/bin/zsh

weekLib=(月 火 水 木 金 土 日)
maxWeek=6
maxVar=5

month=$1
minDay=$2
maxDay=$3
minWeek=`weekCmv $4`
time=$5

if [ "$#" -lt $maxVar ]
then
    echo "Usage: day [month] [minDay] [maxDay] [week] [time]"
else

    while [ $minDay -le $maxDay ]
    do
        if [ $maxWeek -lt $minWeek ]
        then
            minWeek=0
        fi
        
        echo $month/$minDay'('${weekLib[$minWeek]}')' $time
        minDay=$((minDay+1))
        minWeek=$((minWeek+1))
    done
fi
