#!/bin/zsh

week=(月 火 水 木 金 土 日)

if [ "$1" = "月" ]
then
    num=0

elif [ "$1" = "火" ]
then
    num=1

elif [ "$1" = "水" ]
then
    num=2
    
elif [ "$1" = "木" ]
then
    num=3

    elif [ "$1" = "金" ]
then
    num=4

    elif [ "$1" = "土" ]
then
    num=5

elif [ "$1" = "日" ]
then
    num=6

else
    echo "Usage: week is 月-日"
fi

echo $num
